version: "3"
services:
  postgres_car_book:
    container_name: postgres_car_book
    restart: always
    image: car_book/postgres
    build: ./postgres
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
